### ISSUE TITLE
Trying to install pyDarwin but got ssl certificate error

### ISSUE THREAD

**Issue by snailittle** [certara/pyDarwin#33]
I am using a corporate computer and I always seem to have ssl error. Do you know how to et around it? 

Tried command "pip install pyDarwin-Certara --index-url https://certara.jfrog.io/artifactory/api/pypi/certara-pypi-release-public/simple --extra-index-url https://pypi.python.org/simple/",  

but got errors:  "Could not fetch URL https://pypi.python.org/simple/pydarwin-certara/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/pydarwin-certara/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))) - skipping"

**Comment by snailittle** [comment]
I tried the below command and it worked
 pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org pyDarwin

Collecting pyDarwin
  Downloading pydarwin-0.0.4-py3-none-any.whl (5.8 kB)
Installing collected packages: pyDarwin
Successfully installed pyDarwin-0.0.4

**Comment by snailittle** [comment]
Somehow the version doesn't look right.  It reports I was installing 0.0.4 while the latest version is 1.0.  Is there any way to get around the SSL problem?

**Comment by certara-jcraig** [comment]
Hi @snailittle , the package name to [install from pypi repo](https://certara.github.io/pyDarwin/html/Install.html#install-pydarwin) is called pyDarwin-Certara. 

Can you please try specifying the additional ``-trusted-host`` option, as given in below command, and report back whether you are able to install the package given your corporate security policies?

```
pip install pyDarwin-Certara --index-url https://certara.jfrog.io/artifactory/api/pypi/certara-pypi-release-public/simple --extra-index-url https://pypi.python.org/simple/ --trusted-host certara.jfrog.io
```

**Comment by snailittle** [comment]
Used this command and finally got the installation through.  It seems different dependencies are coming from different sites. 
 So I defined many trusted-host

pip install pyDarwin-Certara --index-url https://certara.jfrog.io/artifactory/api/pypi/certara-pypi-release-public/simple --extra-index-url https://pypi.python.org/simple/ --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org --trusted-host=certara.jfrog.io --trusted-host=jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com
