### ISSUE TITLE
Trying to run test file, but error saying "darwin not found"

### ISSUE THREAD

**Issue by snailittle** [certara/pyDarwin#34]
Any idea about the error?  

I run the following within the Example1 folder: 
Documents\pyDarwin-1.0.0\examples\user\Example1>python -m darwin.run_search template.txt tokens.json options.json

C:\Users\zhup3107\AppData\Local\Programs\Python\Python310\python.exe: Error while finding module specification for 'darwin.run_search' (ModuleNotFoundError: No module named 'darwin')

My pyDarwin was installed as below: 
>pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org pyDarwin

Collecting pyDarwin
  Downloading pydarwin-0.0.4-py3-none-any.whl (5.8 kB)
Installing collected packages: pyDarwin
Successfully installed pyDarwin-0.0.4

**Comment by certara-jcraig** [comment]
Duplicated from issue https://github.com/certara/pyDarwin/issues/33
