### ISSUE TITLE
use pyDarwin on python 3.9

### ISSUE THREAD

**Issue by shihao94** [certara/pyDarwin#77]
Hi! Thanks for your nice work! 

We are trying to test this package but I can only install python up to 3.9 within the company computing environment. I wonder if I can still install and use this package? Thanks!

**Comment by certara-msale** [comment]
Not sure, I'll follow up with our developers

**Comment by certara-msale** [comment]
Shihao, Checked with developers, running with python 3.9 does indeed throw errors, without further investigation we don't know exactly where they are coming from.  Not clear (but unlikely) that we'll be able to make it compatible with older versions (but we do plan compatibility with 3.12 in the next release, which is new, the current release isn't compatible with 3.12.
Sorry, not sure we can help you.
Mark

**Comment by shihao94** [comment]
Hi Mark, thanks for your reply and efforts. Look forward to the new release.

**Comment by certara-msale** [comment]
Shihao, we actually discussed this at our scrum this morning and the decision was made that we will not be supporting python 3.9, as there is less than a year of support expected for that version of python.  thanks for understanding.
